/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author acer
 */
public class pabrik extends masterview {

    /**
     * Creates new form sawah
     */
    public pabrik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmap = new javax.swing.JButton();
        mesin1 = new javax.swing.JButton();
        mesin2 = new javax.swing.JButton();
        mesin3 = new javax.swing.JButton();
        mesin4 = new javax.swing.JButton();
        gambarmesin4 = new javax.swing.JLabel();
        gambarmesin1 = new javax.swing.JLabel();
        gambarmesin3 = new javax.swing.JLabel();
        gambarmesin2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmap.setText("map");
        btnmap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmapActionPerformed(evt);
            }
        });
        getContentPane().add(btnmap, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 10, 130, 90));

        mesin1.setBorderPainted(false);
        mesin1.setContentAreaFilled(false);
        mesin1.setFocusPainted(false);
        mesin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesin1MouseClicked(evt);
            }
        });
        getContentPane().add(mesin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 270, 250));

        mesin2.setBorderPainted(false);
        mesin2.setContentAreaFilled(false);
        mesin2.setFocusPainted(false);
        mesin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesin2MouseClicked(evt);
            }
        });
        getContentPane().add(mesin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 260, 250));

        mesin3.setBorderPainted(false);
        mesin3.setContentAreaFilled(false);
        mesin3.setFocusPainted(false);
        mesin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesin3MouseClicked(evt);
            }
        });
        getContentPane().add(mesin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 280, 250));

        mesin4.setBorderPainted(false);
        mesin4.setContentAreaFilled(false);
        mesin4.setFocusPainted(false);
        mesin4.setVerifyInputWhenFocusTarget(false);
        mesin4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesin4MouseClicked(evt);
            }
        });
        getContentPane().add(mesin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 260, 250));

        gambarmesin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mesin.png"))); // NOI18N
        getContentPane().add(gambarmesin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 250, 260));

        gambarmesin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mesin.png"))); // NOI18N
        getContentPane().add(gambarmesin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 270, 250));

        gambarmesin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mesin.png"))); // NOI18N
        getContentPane().add(gambarmesin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, 250, 260));

        gambarmesin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mesin.png"))); // NOI18N
        gambarmesin2.setToolTipText("");
        getContentPane().add(gambarmesin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 270, 250));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmapActionPerformed
        setwindows(new map());
    }//GEN-LAST:event_btnmapActionPerformed

    private void mesin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesin1MouseClicked
        seticongif("mesingif", gambarmesin1);
    }//GEN-LAST:event_mesin1MouseClicked

    private void mesin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesin3MouseClicked
        seticongif("mesingif", gambarmesin3);
    }//GEN-LAST:event_mesin3MouseClicked

    private void mesin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesin2MouseClicked
      seticongif("mesingif", gambarmesin2);
    }//GEN-LAST:event_mesin2MouseClicked

    private void mesin4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesin4MouseClicked
      seticongif("mesingif", gambarmesin4);
    }//GEN-LAST:event_mesin4MouseClicked
    public void seticongif(String file, JLabel btn) {
        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/"+file+".gif")));
    }

    public void seticonpng(String file, JLabel btn) {
        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/"+file+".png")));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pabrik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnmap;
    private javax.swing.JLabel gambarmesin1;
    private javax.swing.JLabel gambarmesin2;
    private javax.swing.JLabel gambarmesin3;
    private javax.swing.JLabel gambarmesin4;
    private javax.swing.JButton mesin1;
    private javax.swing.JButton mesin2;
    private javax.swing.JButton mesin3;
    private javax.swing.JButton mesin4;
    // End of variables declaration//GEN-END:variables
}
