/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.muser;

/**
 *
 * @author acer
 */
public class mainmenu extends masterview {

    /**
     * Creates new form mainmenu
     */
    muser modeluser;

    public mainmenu() {
        try {
            initComponents();
            modeluser = new muser();
        } catch (SQLException ex) {
            Logger.getLogger(mainmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnexit = new javax.swing.JButton();
        btnplay = new javax.swing.JButton();
        btnhelp = new javax.swing.JButton();
        btnscore = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/b_back.png"))); // NOI18N
        btnexit.setBorderPainted(false);
        btnexit.setContentAreaFilled(false);
        btnexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnexit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/b_back2.png"))); // NOI18N
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 130, 120));

        btnplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn_play.png"))); // NOI18N
        btnplay.setBorderPainted(false);
        btnplay.setContentAreaFilled(false);
        btnplay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnplay.setFocusPainted(false);
        btnplay.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn_play2.png"))); // NOI18N
        btnplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplayActionPerformed(evt);
            }
        });
        getContentPane().add(btnplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 420, 110));

        btnhelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn_help.png"))); // NOI18N
        btnhelp.setBorderPainted(false);
        btnhelp.setContentAreaFilled(false);
        btnhelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhelp.setFocusPainted(false);
        btnhelp.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn_help2.png"))); // NOI18N
        btnhelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhelpActionPerformed(evt);
            }
        });
        getContentPane().add(btnhelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 400, 100));

        btnscore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn_hs.png"))); // NOI18N
        btnscore.setBorderPainted(false);
        btnscore.setContentAreaFilled(false);
        btnscore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnscore.setFocusPainted(false);
        btnscore.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn_hg2.png"))); // NOI18N
        btnscore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnscoreActionPerformed(evt);
            }
        });
        getContentPane().add(btnscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 510, 610, 130));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bgmainmenu.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplayActionPerformed
        try {
            String nama = "abcd";
//            String nama = JOptionPane.showInputDialog("masukan nama anda");
            System.out.println("nama = "+nama);
            modeluser.tambahuser(nama);
            setwindows(new map(modeluser.getiduser(nama)));
//            System.out.println("id user ="+modeluser.getiduser("abcd"));
        } catch (SQLException ex) {
            Logger.getLogger(mainmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnplayActionPerformed

    private void btnhelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhelpActionPerformed
        setwindows(new help());
    }//GEN-LAST:event_btnhelpActionPerformed

    private void btnscoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnscoreActionPerformed
        setwindows(new score());
    }//GEN-LAST:event_btnscoreActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnhelp;
    private javax.swing.JButton btnplay;
    private javax.swing.JButton btnscore;
    // End of variables declaration//GEN-END:variables
}
