/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import model.mbarang;
import model.muser;

/**
 *
 * @author acer
 */
public class map extends masterview {

    /**
     * Creates new form play
     */
    String id;
    mbarang modelbarang;
    muser modeluser;

    public map(String id) {
        initComponents();
        this.setVisible(true);
        start();
        try {
            modeluser = new muser();
            modelbarang = new mbarang();
            setupgradebarang();
            this.id = id;
        } catch (SQLException ex) {
            Logger.getLogger(map.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setupgradebarang() throws SQLException {
        String data[] = modeluser.getupdatebarang(id);
        for (int i = 0; i < 4; i++) {
            setdetikloop[i] = Integer.parseInt(data[i + 1]);
        }
    }

    public void start() {
        mytimer.schedule(cek, 1000, 1000);//detik asli
    }

    public void stoptimer(boolean set) {
        stopgame = set;
    }
    
    TimerTask cek = new TimerTask() {
        @Override
        public void run() {
            if (!stopgame) {
                detik++;
                System.out.println("cek " + detik);
                for (int i = 0; i < 4; i++) {
                    if (loop[i]) {
                        System.out.println("ada yang true");
                        loop[i] = false;
                        getdetik[i] = detik + setdetikloop[i];
                        System.out.println("get detik " + getdetik[0]);
                    }
                    if (getdetik[i] == detik) {
                        seticonpngloop(i);
                        System.out.println("ganti png");
                    }
                }
            }
        }
    };

    public void seticonpngloop(int i) {
        System.out.println("seticonpngloop");
        if (i == 0) {
            seticonpng("mesin", labelmesin1);
        }
        if (i == 1) {
            seticonpng("mesin", labelmesin2);
        }
        if (i == 2) {
            seticonpng("mesinjadi", labelmesinjadi1);
        }
        if (i == 3) {
            seticonpng("mesinjadi", labelmesinjadi2);
        }
    }

    public void setgudangfinish() {
        try {
            String data[] = modelbarang.cekbarang(id);
            txtserealcoklat.setText(data[13]);
            txtserealkeju.setText(data[14]);
            txtturbo.setText(data[15]);
        } catch (SQLException ex) {
            Logger.getLogger(map.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setgudangppic() {
        try {
            String data[] = modelbarang.cekbarang(id);
            txtbbjagung.setText(data[5]);
            txtbbgandum.setText(data[6]);
            txtbbsusu.setText(data[7]);
            txtbbgula.setText(data[8]);
            txtbmsereal.setText(data[9]);
            txtbmcoklat.setText(data[10]);
            txtbmplastik.setText(data[11]);
            txtbmkeju.setText(data[12]);
            txtbbjagung1.setText(data[5]);
            txtbbgandum1.setText(data[6]);
            txtbbsusu1.setText(data[7]);
            txtbbgula1.setText(data[8]);
            txtbmsereal1.setText(data[9]);
            txtbmcoklat1.setText(data[10]);
            txtbmplastik1.setText(data[11]);
            txtbmkeju1.setText(data[12]);
        } catch (SQLException ex) {
            Logger.getLogger(map.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelutama = new diu.swe.habib.JPanelSlider.JPanelSlider();
        panelmap = new javax.swing.JPanel();
        btnparik = new javax.swing.JButton();
        btnsawah = new javax.swing.JButton();
        btnmarketing = new javax.swing.JButton();
        btngudangppic = new javax.swing.JButton();
        btngudangfinsih = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        panelmarketing = new javax.swing.JPanel();
        btnmap2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        background3 = new javax.swing.JLabel();
        panelsawah = new javax.swing.JPanel();
        btnmap4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        background5 = new javax.swing.JLabel();
        panelgudangppic = new javax.swing.JPanel();
        btnmap3 = new javax.swing.JButton();
        panelbahan = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtbbjagung = new javax.swing.JLabel();
        txtbbgandum = new javax.swing.JLabel();
        txtbbsusu = new javax.swing.JLabel();
        txtbbgula = new javax.swing.JLabel();
        txtbmsereal = new javax.swing.JLabel();
        txtbmcoklat = new javax.swing.JLabel();
        txtbmkeju = new javax.swing.JLabel();
        txtbmplastik = new javax.swing.JLabel();
        background4 = new javax.swing.JLabel();
        panelpabrik = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        updatemesin1 = new javax.swing.JButton();
        updatemesin2 = new javax.swing.JButton();
        updatemesinjadi1 = new javax.swing.JButton();
        updatemesinjadi2 = new javax.swing.JButton();
        btnmap1 = new javax.swing.JButton();
        tmbmesinjadi1 = new javax.swing.JButton();
        tmbmesin1 = new javax.swing.JButton();
        tmbmesin2 = new javax.swing.JButton();
        labelmesin2 = new javax.swing.JLabel();
        labelmesin1 = new javax.swing.JLabel();
        labelmesinjadi1 = new javax.swing.JLabel();
        tmbmesinjadi2 = new javax.swing.JButton();
        labelmesinjadi2 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        panelbahan1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtbbjagung1 = new javax.swing.JLabel();
        txtbbgandum1 = new javax.swing.JLabel();
        txtbbsusu1 = new javax.swing.JLabel();
        txtbbgula1 = new javax.swing.JLabel();
        txtbmsereal1 = new javax.swing.JLabel();
        txtbmcoklat1 = new javax.swing.JLabel();
        txtbmkeju1 = new javax.swing.JLabel();
        txtbmplastik1 = new javax.swing.JLabel();
        panelgudangfinish = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnmap = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtturbo = new javax.swing.JLabel();
        txtserealcoklat = new javax.swing.JLabel();
        txtserealkeju = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        panelmap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnparik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik1.png"))); // NOI18N
        btnparik.setBorderPainted(false);
        btnparik.setContentAreaFilled(false);
        btnparik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnparik.setFocusPainted(false);
        btnparik.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik2.png"))); // NOI18N
        btnparik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnparikMouseClicked(evt);
            }
        });
        btnparik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparikActionPerformed(evt);
            }
        });
        panelmap.add(btnparik, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 270, 240));

        btnsawah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sawah1.png"))); // NOI18N
        btnsawah.setBorderPainted(false);
        btnsawah.setContentAreaFilled(false);
        btnsawah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsawah.setFocusPainted(false);
        btnsawah.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sawah2.png"))); // NOI18N
        btnsawah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsawahMouseClicked(evt);
            }
        });
        panelmap.add(btnsawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 300, 290));

        btnmarketing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/seller1.png"))); // NOI18N
        btnmarketing.setBorderPainted(false);
        btnmarketing.setContentAreaFilled(false);
        btnmarketing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmarketing.setFocusPainted(false);
        btnmarketing.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/seller2.png"))); // NOI18N
        btnmarketing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmarketingMouseClicked(evt);
            }
        });
        panelmap.add(btnmarketing, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 480, 300, 270));

        btngudangppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ppic1.png"))); // NOI18N
        btngudangppic.setBorderPainted(false);
        btngudangppic.setContentAreaFilled(false);
        btngudangppic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btngudangppic.setFocusPainted(false);
        btngudangppic.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ppic2.png"))); // NOI18N
        btngudangppic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngudangppicMouseClicked(evt);
            }
        });
        btngudangppic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngudangppicActionPerformed(evt);
            }
        });
        panelmap.add(btngudangppic, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 320, 290));

        btngudangfinsih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/FG1.png"))); // NOI18N
        btngudangfinsih.setBorderPainted(false);
        btngudangfinsih.setContentAreaFilled(false);
        btngudangfinsih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btngudangfinsih.setFocusPainted(false);
        btngudangfinsih.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/FG2.png"))); // NOI18N
        btngudangfinsih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngudangfinsihMouseClicked(evt);
            }
        });
        panelmap.add(btngudangfinsih, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 290, 260));

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/b_back.png"))); // NOI18N
        btnexit.setBorderPainted(false);
        btnexit.setContentAreaFilled(false);
        btnexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnexit.setFocusPainted(false);
        btnexit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/b_back2.png"))); // NOI18N
        btnexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexitMouseClicked(evt);
            }
        });
        panelmap.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 140, 130));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bgmap.png"))); // NOI18N
        panelmap.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1360, 770));

        panelutama.add(panelmap, "card2");

        panelmarketing.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmap2.setText("map");
        btnmap2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmap2ActionPerformed(evt);
            }
        });
        panelmarketing.add(btnmap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 10, 130, 90));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        panelmarketing.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 220, 390));
        panelmarketing.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 120, 40));
        panelmarketing.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 240, 80));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Avatar.gif"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
        panelmarketing.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 170, 240, 370));
        jButton6.getAccessibleContext().setAccessibleDescription("");

        panelmarketing.add(background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        panelutama.add(panelmarketing, "card3");

        panelsawah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmap4.setText("map");
        btnmap4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmap4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmap4ActionPerformed(evt);
            }
        });
        panelsawah.add(btnmap4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 660, 130, 90));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tpanen1.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tpanen2.png"))); // NOI18N
        panelsawah.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 120, 170, 160));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/air.png"))); // NOI18N
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setFocusPainted(false);
        jButton13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/air1.png"))); // NOI18N
        panelsawah.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 280, 170, 160));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ttanam1.png"))); // NOI18N
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setFocusPainted(false);
        jButton15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ttanam2.png"))); // NOI18N
        panelsawah.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 440, 170, 160));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sawah.png"))); // NOI18N
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setFocusPainted(false);
        panelsawah.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -12, 1380, 780));
        panelsawah.add(background5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        panelutama.add(panelsawah, "card3");

        panelgudangppic.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmap3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map1.png"))); // NOI18N
        btnmap3.setText("map");
        btnmap3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmap3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmap3ActionPerformed(evt);
            }
        });
        panelgudangppic.add(btnmap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 660, 130, 90));

        panelbahan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bm_plastik.png"))); // NOI18N
        panelbahan.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 90, 60));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bm_keju.png"))); // NOI18N
        panelbahan.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 90, 60));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bm_coklat.png"))); // NOI18N
        panelbahan.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 90, 60));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bm_sereal.png"))); // NOI18N
        panelbahan.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 90, 60));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bm_gula.png"))); // NOI18N
        panelbahan.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 90, 60));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bm_susu.png"))); // NOI18N
        panelbahan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 90, 60));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bb_gandum.png"))); // NOI18N
        panelbahan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 90, 60));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bb_jagung.png"))); // NOI18N
        panelbahan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 60));

        txtbbjagung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelbahan.add(txtbbjagung, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, 30));

        txtbbgandum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelbahan.add(txtbbgandum, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 70, 30));

        txtbbsusu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelbahan.add(txtbbsusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 70, 30));

        txtbbgula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelbahan.add(txtbbgula, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 70, 30));

        txtbmsereal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelbahan.add(txtbmsereal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 70, 30));

        txtbmcoklat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelbahan.add(txtbmcoklat, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 70, 30));

        txtbmkeju.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelbahan.add(txtbmkeju, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 70, 30));

        txtbmplastik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelbahan.add(txtbmplastik, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 70, 30));

        panelgudangppic.add(panelbahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 140));

        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bgppic.png"))); // NOI18N
        panelgudangppic.add(background4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        panelutama.add(panelgudangppic, "card3");

        panelpabrik.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("update");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 5, -1, -1));

        updatemesin1.setText("mesin1");
        updatemesin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatemesin1ActionPerformed(evt);
            }
        });
        jPanel1.add(updatemesin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        updatemesin2.setText("mesin2");
        updatemesin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatemesin2ActionPerformed(evt);
            }
        });
        jPanel1.add(updatemesin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        updatemesinjadi1.setText("mesinjadi1");
        updatemesinjadi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatemesinjadi1ActionPerformed(evt);
            }
        });
        jPanel1.add(updatemesinjadi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, -1));

        updatemesinjadi2.setText("mesinjadi2");
        updatemesinjadi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatemesinjadi2ActionPerformed(evt);
            }
        });
        jPanel1.add(updatemesinjadi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, -1, -1));

        panelpabrik.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 990, 440));

        btnmap1.setText("map");
        btnmap1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmap1ActionPerformed(evt);
            }
        });
        panelpabrik.add(btnmap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 10, 130, 90));

        tmbmesinjadi1.setBorderPainted(false);
        tmbmesinjadi1.setContentAreaFilled(false);
        tmbmesinjadi1.setFocusPainted(false);
        tmbmesinjadi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmbmesinjadi1MouseClicked(evt);
            }
        });
        tmbmesinjadi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbmesinjadi1ActionPerformed(evt);
            }
        });
        panelpabrik.add(tmbmesinjadi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 350, 340));

        tmbmesin1.setBorderPainted(false);
        tmbmesin1.setContentAreaFilled(false);
        tmbmesin1.setFocusPainted(false);
        tmbmesin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmbmesin1MouseClicked(evt);
            }
        });
        tmbmesin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbmesin1ActionPerformed(evt);
            }
        });
        panelpabrik.add(tmbmesin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 280, 250));

        tmbmesin2.setBorderPainted(false);
        tmbmesin2.setContentAreaFilled(false);
        tmbmesin2.setFocusPainted(false);
        tmbmesin2.setVerifyInputWhenFocusTarget(false);
        tmbmesin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmbmesin2MouseClicked(evt);
            }
        });
        tmbmesin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbmesin2ActionPerformed(evt);
            }
        });
        panelpabrik.add(tmbmesin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 370, 260, 250));

        labelmesin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mesin.png"))); // NOI18N
        panelpabrik.add(labelmesin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 370, 250, 260));

        labelmesin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mesin.png"))); // NOI18N
        panelpabrik.add(labelmesin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 100, 250, 260));

        labelmesinjadi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mesinjadi.png"))); // NOI18N
        labelmesinjadi1.setToolTipText("");
        panelpabrik.add(labelmesinjadi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 350, 340));

        tmbmesinjadi2.setBorderPainted(false);
        tmbmesinjadi2.setContentAreaFilled(false);
        tmbmesinjadi2.setFocusPainted(false);
        tmbmesinjadi2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmbmesinjadi2MouseClicked(evt);
            }
        });
        tmbmesinjadi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbmesinjadi2ActionPerformed(evt);
            }
        });
        panelpabrik.add(tmbmesinjadi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 350, 330));

        labelmesinjadi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mesinjadi.png"))); // NOI18N
        labelmesinjadi2.setToolTipText("");
        panelpabrik.add(labelmesinjadi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 350, 340));
        panelpabrik.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1370, 770));

        panelbahan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bm_plastik.png"))); // NOI18N
        panelbahan1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 90, 60));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bm_keju.png"))); // NOI18N
        panelbahan1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 90, 60));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bm_coklat.png"))); // NOI18N
        panelbahan1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 90, 60));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bm_sereal.png"))); // NOI18N
        panelbahan1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 90, 60));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bm_gula.png"))); // NOI18N
        panelbahan1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 90, 60));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bm_susu.png"))); // NOI18N
        panelbahan1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 90, 60));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bb_gandum.png"))); // NOI18N
        panelbahan1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 90, 60));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bb_jagung.png"))); // NOI18N
        panelbahan1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 60));

        txtbbjagung1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelbahan1.add(txtbbjagung1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, 30));

        txtbbgandum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelbahan1.add(txtbbgandum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 70, 30));

        txtbbsusu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelbahan1.add(txtbbsusu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 70, 30));

        txtbbgula1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelbahan1.add(txtbbgula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 70, 30));

        txtbmsereal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelbahan1.add(txtbmsereal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 70, 30));

        txtbmcoklat1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelbahan1.add(txtbmcoklat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 70, 30));

        txtbmkeju1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelbahan1.add(txtbmkeju1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 70, 30));

        txtbmplastik1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelbahan1.add(txtbmplastik1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 70, 30));

        panelpabrik.add(panelbahan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 140));

        panelutama.add(panelpabrik, "card3");

        panelgudangfinish.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bjserealkeju.png"))); // NOI18N
        panelgudangfinish.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 160, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bjturbo.png"))); // NOI18N
        panelgudangfinish.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 310, 140, 150));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bjserealcoklat.png"))); // NOI18N
        panelgudangfinish.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 110, 150));

        btnmap.setText("map");
        btnmap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmapActionPerformed(evt);
            }
        });
        panelgudangfinish.add(btnmap, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 10, 130, 90));
        panelgudangfinish.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 150, 70));
        panelgudangfinish.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 150, 70));
        panelgudangfinish.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 520, 140, 70));

        txtturbo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtturbo.setText("jLabel4");
        panelgudangfinish.add(txtturbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 80, 30));

        txtserealcoklat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtserealcoklat.setText("jLabel4");
        panelgudangfinish.add(txtserealcoklat, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 80, 30));

        txtserealkeju.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtserealkeju.setText("jLabel4");
        panelgudangfinish.add(txtserealkeju, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 80, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        panelgudangfinish.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, 300));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bggudang.jpg"))); // NOI18N
        panelgudangfinish.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        panelutama.add(panelgudangfinish, "card3");

        getContentPane().add(panelutama, "card8");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsawahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsawahMouseClicked
//        setwindows(new sawah());
        panelutama.nextPanel(25, panelsawah, panelutama.right);
    }//GEN-LAST:event_btnsawahMouseClicked

    private void btngudangppicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngudangppicMouseClicked
//        setwindows(new gudangppic());
        setgudangppic();
        panelutama.nextPanel(25, panelgudangppic, panelutama.right);
    }//GEN-LAST:event_btngudangppicMouseClicked

    private void btnmarketingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmarketingMouseClicked
//        setwindows(new marketing());
        panelutama.nextPanel(25, panelmarketing, panelutama.right);
    }//GEN-LAST:event_btnmarketingMouseClicked

    private void btnparikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnparikMouseClicked
//        setwindows(new pabrik());
        setgudangppic();
        panelutama.nextPanel(25, panelpabrik, panelutama.right);
    }//GEN-LAST:event_btnparikMouseClicked

    private void btngudangfinsihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngudangfinsihMouseClicked
//        setwindows(new gudangfinish());
        panelutama.nextPanel(25, panelgudangfinish, panelutama.right);
        setgudangfinish();
    }//GEN-LAST:event_btngudangfinsihMouseClicked

    private void btnexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexitMouseClicked
        setwindows(new mainmenu());
    }//GEN-LAST:event_btnexitMouseClicked

    private void btnparikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnparikActionPerformed

    private void btnmapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmapActionPerformed
//        setwindows(new map());
        panelutama.nextPanel(25, panelmap, panelutama.left);
    }//GEN-LAST:event_btnmapActionPerformed

    private void btnmap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmap1ActionPerformed
//        setwindows(new map());
        panelutama.nextPanel(25, panelmap, panelutama.left);
    }//GEN-LAST:event_btnmap1ActionPerformed

    private void tmbmesinjadi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmbmesinjadi1MouseClicked
    }//GEN-LAST:event_tmbmesinjadi1MouseClicked

    private void tmbmesin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmbmesin1MouseClicked

    }//GEN-LAST:event_tmbmesin1MouseClicked

    private void tmbmesin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmbmesin2MouseClicked

    }//GEN-LAST:event_tmbmesin2MouseClicked

    private void btnmap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmap2ActionPerformed
//        setwindows(new map());
        panelutama.nextPanel(25, panelmap, panelutama.left);
    }//GEN-LAST:event_btnmap2ActionPerformed

    private void btnmap3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmap3ActionPerformed
//        setwindows(new map());
        panelutama.nextPanel(25, panelmap, panelutama.left);
    }//GEN-LAST:event_btnmap3ActionPerformed

    private void btnmap4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmap4ActionPerformed
        //        setwindows(new map());
        panelutama.nextPanel(25, panelmap, panelutama.left);
    }//GEN-LAST:event_btnmap4ActionPerformed

    private void btngudangppicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngudangppicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btngudangppicActionPerformed

    private void tmbmesinjadi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbmesinjadi1ActionPerformed
        seticongif("mesinjadi", labelmesinjadi1);
        loop[2] = true;
    }//GEN-LAST:event_tmbmesinjadi1ActionPerformed

    private void tmbmesin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbmesin1ActionPerformed
        seticongif("mesin", labelmesin1);
        loop[0] = true;
    }//GEN-LAST:event_tmbmesin1ActionPerformed

    private void tmbmesinjadi2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmbmesinjadi2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tmbmesinjadi2MouseClicked

    private void tmbmesinjadi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbmesinjadi2ActionPerformed
        seticongif("mesinjadi", labelmesinjadi2);
        loop[3] = true;
    }//GEN-LAST:event_tmbmesinjadi2ActionPerformed

    private void tmbmesin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbmesin2ActionPerformed
        seticongif("mesin", labelmesin2);
        loop[1] = true;
    }//GEN-LAST:event_tmbmesin2ActionPerformed

    private void updatemesin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatemesin1ActionPerformed
        setdetikloop[0] -= 1;
    }//GEN-LAST:event_updatemesin1ActionPerformed

    private void updatemesin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatemesin2ActionPerformed
        setdetikloop[1] -= 1;
    }//GEN-LAST:event_updatemesin2ActionPerformed

    private void updatemesinjadi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatemesinjadi1ActionPerformed
        setdetikloop[2] -= 1;
    }//GEN-LAST:event_updatemesinjadi1ActionPerformed

    private void updatemesinjadi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatemesinjadi2ActionPerformed
        setdetikloop[0] -=1;
    }//GEN-LAST:event_updatemesinjadi2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background4;
    private javax.swing.JLabel background5;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btngudangfinsih;
    private javax.swing.JButton btngudangppic;
    private javax.swing.JButton btnmap;
    private javax.swing.JButton btnmap1;
    private javax.swing.JButton btnmap2;
    private javax.swing.JButton btnmap3;
    private javax.swing.JButton btnmap4;
    private javax.swing.JButton btnmarketing;
    private javax.swing.JButton btnparik;
    private javax.swing.JButton btnsawah;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelmesin1;
    private javax.swing.JLabel labelmesin2;
    private javax.swing.JLabel labelmesinjadi1;
    private javax.swing.JLabel labelmesinjadi2;
    private javax.swing.JPanel panelbahan;
    private javax.swing.JPanel panelbahan1;
    private javax.swing.JPanel panelgudangfinish;
    private javax.swing.JPanel panelgudangppic;
    private javax.swing.JPanel panelmap;
    private javax.swing.JPanel panelmarketing;
    private javax.swing.JPanel panelpabrik;
    private javax.swing.JPanel panelsawah;
    private diu.swe.habib.JPanelSlider.JPanelSlider panelutama;
    private javax.swing.JButton tmbmesin1;
    private javax.swing.JButton tmbmesin2;
    private javax.swing.JButton tmbmesinjadi1;
    private javax.swing.JButton tmbmesinjadi2;
    private javax.swing.JLabel txtbbgandum;
    private javax.swing.JLabel txtbbgandum1;
    private javax.swing.JLabel txtbbgula;
    private javax.swing.JLabel txtbbgula1;
    private javax.swing.JLabel txtbbjagung;
    private javax.swing.JLabel txtbbjagung1;
    private javax.swing.JLabel txtbbsusu;
    private javax.swing.JLabel txtbbsusu1;
    private javax.swing.JLabel txtbmcoklat;
    private javax.swing.JLabel txtbmcoklat1;
    private javax.swing.JLabel txtbmkeju;
    private javax.swing.JLabel txtbmkeju1;
    private javax.swing.JLabel txtbmplastik;
    private javax.swing.JLabel txtbmplastik1;
    private javax.swing.JLabel txtbmsereal;
    private javax.swing.JLabel txtbmsereal1;
    private javax.swing.JLabel txtserealcoklat;
    private javax.swing.JLabel txtserealkeju;
    private javax.swing.JLabel txtturbo;
    private javax.swing.JButton updatemesin1;
    private javax.swing.JButton updatemesin2;
    private javax.swing.JButton updatemesinjadi1;
    private javax.swing.JButton updatemesinjadi2;
    // End of variables declaration//GEN-END:variables
}
