/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author acer
 */
public class map extends masterview {

    /**
     * Creates new form play
     */
    public map() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnparik = new javax.swing.JButton();
        btnsawah = new javax.swing.JButton();
        btnmarketing = new javax.swing.JButton();
        btngudangppic = new javax.swing.JButton();
        btngudangfinsih = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnparik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik1.png"))); // NOI18N
        btnparik.setBorderPainted(false);
        btnparik.setContentAreaFilled(false);
        btnparik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnparik.setFocusPainted(false);
        btnparik.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik2.png"))); // NOI18N
        btnparik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnparikMouseClicked(evt);
            }
        });
        getContentPane().add(btnparik, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 270, 240));

        btnsawah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sawah1.png"))); // NOI18N
        btnsawah.setBorderPainted(false);
        btnsawah.setContentAreaFilled(false);
        btnsawah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsawah.setFocusPainted(false);
        btnsawah.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sawah2.png"))); // NOI18N
        btnsawah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsawahMouseClicked(evt);
            }
        });
        getContentPane().add(btnsawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 300, 290));

        btnmarketing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/seller1.png"))); // NOI18N
        btnmarketing.setBorderPainted(false);
        btnmarketing.setContentAreaFilled(false);
        btnmarketing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmarketing.setFocusPainted(false);
        btnmarketing.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/seller2.png"))); // NOI18N
        btnmarketing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmarketingMouseClicked(evt);
            }
        });
        getContentPane().add(btnmarketing, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 480, 300, 270));

        btngudangppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ppic1.png"))); // NOI18N
        btngudangppic.setBorderPainted(false);
        btngudangppic.setContentAreaFilled(false);
        btngudangppic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btngudangppic.setFocusPainted(false);
        btngudangppic.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ppic2.png"))); // NOI18N
        btngudangppic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngudangppicMouseClicked(evt);
            }
        });
        getContentPane().add(btngudangppic, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 320, 290));

        btngudangfinsih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/FG1.png"))); // NOI18N
        btngudangfinsih.setBorderPainted(false);
        btngudangfinsih.setContentAreaFilled(false);
        btngudangfinsih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btngudangfinsih.setFocusPainted(false);
        btngudangfinsih.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/FG2.png"))); // NOI18N
        btngudangfinsih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngudangfinsihMouseClicked(evt);
            }
        });
        getContentPane().add(btngudangfinsih, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 290, 260));

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/b_back.png"))); // NOI18N
        btnexit.setBorderPainted(false);
        btnexit.setContentAreaFilled(false);
        btnexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnexit.setFocusPainted(false);
        btnexit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/b_back2.png"))); // NOI18N
        btnexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexitMouseClicked(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 140, 130));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bgmap.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsawahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsawahMouseClicked
        setwindows(new sawah());
    }//GEN-LAST:event_btnsawahMouseClicked

    private void btngudangppicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngudangppicMouseClicked
        setwindows(new gudangppic());
    }//GEN-LAST:event_btngudangppicMouseClicked

    private void btnmarketingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmarketingMouseClicked
        setwindows(new marketing());
    }//GEN-LAST:event_btnmarketingMouseClicked

    private void btnparikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnparikMouseClicked
        setwindows(new pabrik());
    }//GEN-LAST:event_btnparikMouseClicked

    private void btngudangfinsihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngudangfinsihMouseClicked
        setwindows(new gudangfinish());
    }//GEN-LAST:event_btngudangfinsihMouseClicked

    private void btnexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexitMouseClicked
        setwindows(new mainmenu());
    }//GEN-LAST:event_btnexitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new map().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btngudangfinsih;
    private javax.swing.JButton btngudangppic;
    private javax.swing.JButton btnmarketing;
    private javax.swing.JButton btnparik;
    private javax.swing.JButton btnsawah;
    // End of variables declaration//GEN-END:variables
}
