/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.mbarang;

/**
 *
 * @author acer
 */
public class map extends masterview {

    /**
     * Creates new form play
     */
    String id;
    mbarang modelbarang;

    public map(String id) {
        initComponents();
        this.setVisible(true);
        try {
            modelbarang = new mbarang();
            this.id = id;

        } catch (SQLException ex) {
            Logger.getLogger(map.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setgudangfinish() {
        try {
            String data[] = modelbarang.cekbarang(id);
            txtserealcoklat.setText(data[13]);
            txtserealkeju.setText(data[14]);
            txtturbo.setText(data[15]);
        } catch (SQLException ex) {
            Logger.getLogger(map.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setgudangppic() {
        try {
            String data[] = modelbarang.cekbarang(id);
            txtbbjagung.setText(data[5]);
            txtbbgandum.setText(data[6]);
            txtbbsusu.setText(data[7]);
            txtbbgula.setText(data[8]);
            txtbmsereal.setText(data[9]);
            txtbmcoklat.setText(data[10]);
            txtbmplastik.setText(data[11]);
            txtbmkeju.setText(data[12]);
        } catch (SQLException ex) {
            Logger.getLogger(map.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelutama = new diu.swe.habib.JPanelSlider.JPanelSlider();
        panelmap = new javax.swing.JPanel();
        btnparik = new javax.swing.JButton();
        btnsawah = new javax.swing.JButton();
        btnmarketing = new javax.swing.JButton();
        btngudangppic = new javax.swing.JButton();
        btngudangfinsih = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        panelmarketing = new javax.swing.JPanel();
        btnmap2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        background3 = new javax.swing.JLabel();
        panelsawah = new javax.swing.JPanel();
        btnmap4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        background5 = new javax.swing.JLabel();
        panelgudangppic = new javax.swing.JPanel();
        btnmap3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtbbjagung = new javax.swing.JLabel();
        txtbbgandum = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtbbsusu = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtbmsereal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtbmcoklat = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtbmkeju = new javax.swing.JLabel();
        txtbmplastik = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtbbgula = new javax.swing.JLabel();
        background4 = new javax.swing.JLabel();
        panelpabrik = new javax.swing.JPanel();
        btnmap1 = new javax.swing.JButton();
        mesin2 = new javax.swing.JButton();
        mesin3 = new javax.swing.JButton();
        mesin4 = new javax.swing.JButton();
        gambarmesin4 = new javax.swing.JLabel();
        gambarmesin3 = new javax.swing.JLabel();
        iconmesinjadi = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        panelgudangfinish = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnmap = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtturbo = new javax.swing.JLabel();
        txtserealcoklat = new javax.swing.JLabel();
        txtserealkeju = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        panelmap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnparik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik1.png"))); // NOI18N
        btnparik.setBorderPainted(false);
        btnparik.setContentAreaFilled(false);
        btnparik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnparik.setFocusPainted(false);
        btnparik.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pabrik2.png"))); // NOI18N
        btnparik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnparikMouseClicked(evt);
            }
        });
        btnparik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparikActionPerformed(evt);
            }
        });
        panelmap.add(btnparik, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 270, 240));

        btnsawah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sawah1.png"))); // NOI18N
        btnsawah.setBorderPainted(false);
        btnsawah.setContentAreaFilled(false);
        btnsawah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsawah.setFocusPainted(false);
        btnsawah.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sawah2.png"))); // NOI18N
        btnsawah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsawahMouseClicked(evt);
            }
        });
        panelmap.add(btnsawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 300, 290));

        btnmarketing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/seller1.png"))); // NOI18N
        btnmarketing.setBorderPainted(false);
        btnmarketing.setContentAreaFilled(false);
        btnmarketing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmarketing.setFocusPainted(false);
        btnmarketing.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/seller2.png"))); // NOI18N
        btnmarketing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmarketingMouseClicked(evt);
            }
        });
        panelmap.add(btnmarketing, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 480, 300, 270));

        btngudangppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ppic1.png"))); // NOI18N
        btngudangppic.setBorderPainted(false);
        btngudangppic.setContentAreaFilled(false);
        btngudangppic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btngudangppic.setFocusPainted(false);
        btngudangppic.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ppic2.png"))); // NOI18N
        btngudangppic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngudangppicMouseClicked(evt);
            }
        });
        btngudangppic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngudangppicActionPerformed(evt);
            }
        });
        panelmap.add(btngudangppic, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 320, 290));

        btngudangfinsih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/FG1.png"))); // NOI18N
        btngudangfinsih.setBorderPainted(false);
        btngudangfinsih.setContentAreaFilled(false);
        btngudangfinsih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btngudangfinsih.setFocusPainted(false);
        btngudangfinsih.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/FG2.png"))); // NOI18N
        btngudangfinsih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngudangfinsihMouseClicked(evt);
            }
        });
        panelmap.add(btngudangfinsih, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 290, 260));

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/b_back.png"))); // NOI18N
        btnexit.setBorderPainted(false);
        btnexit.setContentAreaFilled(false);
        btnexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnexit.setFocusPainted(false);
        btnexit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/b_back2.png"))); // NOI18N
        btnexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexitMouseClicked(evt);
            }
        });
        panelmap.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 140, 130));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bgmap.png"))); // NOI18N
        panelmap.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1360, 770));

        panelutama.add(panelmap, "card2");

        panelmarketing.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmap2.setText("map");
        btnmap2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmap2ActionPerformed(evt);
            }
        });
        panelmarketing.add(btnmap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 10, 130, 90));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        panelmarketing.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 220, 390));
        panelmarketing.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 120, 40));
        panelmarketing.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 240, 80));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Avatar.gif"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
        panelmarketing.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 170, 240, 370));
        jButton6.getAccessibleContext().setAccessibleDescription("");

        panelmarketing.add(background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        panelutama.add(panelmarketing, "card3");

        panelsawah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmap4.setText("map");
        btnmap4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmap4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmap4ActionPerformed(evt);
            }
        });
        panelsawah.add(btnmap4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 660, 130, 90));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tpanen1.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tpanen2.png"))); // NOI18N
        panelsawah.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 120, 170, 160));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/air.png"))); // NOI18N
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setFocusPainted(false);
        jButton13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/air1.png"))); // NOI18N
        panelsawah.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 280, 170, 160));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ttanam1.png"))); // NOI18N
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setFocusPainted(false);
        jButton15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ttanam2.png"))); // NOI18N
        panelsawah.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 440, 170, 160));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sawah.png"))); // NOI18N
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setFocusPainted(false);
        panelsawah.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -12, 1380, 780));
        panelsawah.add(background5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        panelutama.add(panelsawah, "card3");

        panelgudangppic.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmap3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map1.png"))); // NOI18N
        btnmap3.setText("map");
        btnmap3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmap3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmap3ActionPerformed(evt);
            }
        });
        panelgudangppic.add(btnmap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 660, 130, 90));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bb_jagung.png"))); // NOI18N
        panelgudangppic.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 60));

        txtbbjagung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelgudangppic.add(txtbbjagung, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, 30));

        txtbbgandum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelgudangppic.add(txtbbgandum, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 70, 30));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bb_gandum.png"))); // NOI18N
        panelgudangppic.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 90, 60));

        txtbbsusu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelgudangppic.add(txtbbsusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 70, 30));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bm_susu.png"))); // NOI18N
        panelgudangppic.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 90, 60));

        txtbmsereal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelgudangppic.add(txtbmsereal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 70, 30));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bm_sereal.png"))); // NOI18N
        panelgudangppic.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 90, 60));

        txtbmcoklat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelgudangppic.add(txtbmcoklat, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 70, 30));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bm_coklat.png"))); // NOI18N
        panelgudangppic.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 90, 60));

        txtbmkeju.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelgudangppic.add(txtbmkeju, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 70, 30));

        txtbmplastik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelgudangppic.add(txtbmplastik, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 70, 30));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bm_plastik.png"))); // NOI18N
        panelgudangppic.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 90, 60));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bm_keju.png"))); // NOI18N
        panelgudangppic.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 90, 60));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bm_gula.png"))); // NOI18N
        panelgudangppic.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 90, 60));

        txtbbgula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelgudangppic.add(txtbbgula, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 70, 30));

        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bgppic.png"))); // NOI18N
        panelgudangppic.add(background4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        panelutama.add(panelgudangppic, "card3");

        panelpabrik.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmap1.setText("map");
        btnmap1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmap1ActionPerformed(evt);
            }
        });
        panelpabrik.add(btnmap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 10, 130, 90));

        mesin2.setBorderPainted(false);
        mesin2.setContentAreaFilled(false);
        mesin2.setFocusPainted(false);
        mesin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesin2MouseClicked(evt);
            }
        });
        mesin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesin2ActionPerformed(evt);
            }
        });
        panelpabrik.add(mesin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 350, 350));

        mesin3.setBorderPainted(false);
        mesin3.setContentAreaFilled(false);
        mesin3.setFocusPainted(false);
        mesin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesin3MouseClicked(evt);
            }
        });
        panelpabrik.add(mesin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 280, 250));

        mesin4.setBorderPainted(false);
        mesin4.setContentAreaFilled(false);
        mesin4.setFocusPainted(false);
        mesin4.setVerifyInputWhenFocusTarget(false);
        mesin4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesin4MouseClicked(evt);
            }
        });
        panelpabrik.add(mesin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 350, 260, 250));

        gambarmesin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mesin.png"))); // NOI18N
        panelpabrik.add(gambarmesin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 250, 260));

        gambarmesin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mesin.png"))); // NOI18N
        panelpabrik.add(gambarmesin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, 250, 260));

        iconmesinjadi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mesindiam.png"))); // NOI18N
        iconmesinjadi.setToolTipText("");
        panelpabrik.add(iconmesinjadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 350, 340));
        panelpabrik.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 1370, 770));

        panelutama.add(panelpabrik, "card3");

        panelgudangfinish.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bjserealkeju.png"))); // NOI18N
        panelgudangfinish.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 160, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bjturbo.png"))); // NOI18N
        panelgudangfinish.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 310, 140, 150));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bjserealcoklat.png"))); // NOI18N
        panelgudangfinish.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 110, 150));

        btnmap.setText("map");
        btnmap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmapActionPerformed(evt);
            }
        });
        panelgudangfinish.add(btnmap, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 10, 130, 90));
        panelgudangfinish.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 150, 70));
        panelgudangfinish.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 150, 70));
        panelgudangfinish.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 520, 140, 70));

        txtturbo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtturbo.setText("jLabel4");
        panelgudangfinish.add(txtturbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 80, 30));

        txtserealcoklat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtserealcoklat.setText("jLabel4");
        panelgudangfinish.add(txtserealcoklat, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 80, 30));

        txtserealkeju.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtserealkeju.setText("jLabel4");
        panelgudangfinish.add(txtserealkeju, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 80, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        panelgudangfinish.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, 300));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bggudang.jpg"))); // NOI18N
        panelgudangfinish.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        panelutama.add(panelgudangfinish, "card3");

        getContentPane().add(panelutama, "card8");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsawahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsawahMouseClicked
//        setwindows(new sawah());
        panelutama.nextPanel(25, panelsawah, panelutama.right);
    }//GEN-LAST:event_btnsawahMouseClicked

    private void btngudangppicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngudangppicMouseClicked
//        setwindows(new gudangppic());
        setgudangppic();
        panelutama.nextPanel(25, panelgudangppic, panelutama.right);
    }//GEN-LAST:event_btngudangppicMouseClicked

    private void btnmarketingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmarketingMouseClicked
//        setwindows(new marketing());
        panelutama.nextPanel(25, panelmarketing, panelutama.right);
    }//GEN-LAST:event_btnmarketingMouseClicked

    private void btnparikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnparikMouseClicked
//        setwindows(new pabrik());
        panelutama.nextPanel(25, panelpabrik, panelutama.right);
    }//GEN-LAST:event_btnparikMouseClicked

    private void btngudangfinsihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngudangfinsihMouseClicked
//        setwindows(new gudangfinish());
        panelutama.nextPanel(25, panelgudangfinish, panelutama.right);
        setgudangfinish();
    }//GEN-LAST:event_btngudangfinsihMouseClicked

    private void btnexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexitMouseClicked
        setwindows(new mainmenu());
    }//GEN-LAST:event_btnexitMouseClicked

    private void btnparikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnparikActionPerformed

    private void btnmapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmapActionPerformed
//        setwindows(new map());
        panelutama.nextPanel(25, panelmap, panelutama.left);
    }//GEN-LAST:event_btnmapActionPerformed

    private void btnmap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmap1ActionPerformed
//        setwindows(new map());
        panelutama.nextPanel(25, panelmap, panelutama.left);
    }//GEN-LAST:event_btnmap1ActionPerformed

    private void mesin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesin2MouseClicked
        seticongif("mesingif", iconmesinjadi);
    }//GEN-LAST:event_mesin2MouseClicked

    private void mesin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesin3MouseClicked
        seticongif("mesingif", gambarmesin3);
    }//GEN-LAST:event_mesin3MouseClicked

    private void mesin4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesin4MouseClicked
        seticongif("mesingif", gambarmesin4);
    }//GEN-LAST:event_mesin4MouseClicked

    private void btnmap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmap2ActionPerformed
//        setwindows(new map());
        panelutama.nextPanel(25, panelmap, panelutama.left);
    }//GEN-LAST:event_btnmap2ActionPerformed

    private void btnmap3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmap3ActionPerformed
//        setwindows(new map());
        panelutama.nextPanel(25, panelmap, panelutama.left);
    }//GEN-LAST:event_btnmap3ActionPerformed

    private void btnmap4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmap4ActionPerformed
        //        setwindows(new map());
        panelutama.nextPanel(25, panelmap, panelutama.left);
    }//GEN-LAST:event_btnmap4ActionPerformed

    private void btngudangppicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngudangppicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btngudangppicActionPerformed

    private void mesin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesin2ActionPerformed
        seticongif("mesin2", iconmesinjadi);
    }//GEN-LAST:event_mesin2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background4;
    private javax.swing.JLabel background5;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btngudangfinsih;
    private javax.swing.JButton btngudangppic;
    private javax.swing.JButton btnmap;
    private javax.swing.JButton btnmap1;
    private javax.swing.JButton btnmap2;
    private javax.swing.JButton btnmap3;
    private javax.swing.JButton btnmap4;
    private javax.swing.JButton btnmarketing;
    private javax.swing.JButton btnparik;
    private javax.swing.JButton btnsawah;
    private javax.swing.JLabel gambarmesin3;
    private javax.swing.JLabel gambarmesin4;
    private javax.swing.JLabel iconmesinjadi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton mesin2;
    private javax.swing.JButton mesin3;
    private javax.swing.JButton mesin4;
    private javax.swing.JPanel panelgudangfinish;
    private javax.swing.JPanel panelgudangppic;
    private javax.swing.JPanel panelmap;
    private javax.swing.JPanel panelmarketing;
    private javax.swing.JPanel panelpabrik;
    private javax.swing.JPanel panelsawah;
    private diu.swe.habib.JPanelSlider.JPanelSlider panelutama;
    private javax.swing.JLabel txtbbgandum;
    private javax.swing.JLabel txtbbgula;
    private javax.swing.JLabel txtbbjagung;
    private javax.swing.JLabel txtbbsusu;
    private javax.swing.JLabel txtbmcoklat;
    private javax.swing.JLabel txtbmkeju;
    private javax.swing.JLabel txtbmplastik;
    private javax.swing.JLabel txtbmsereal;
    private javax.swing.JLabel txtserealcoklat;
    private javax.swing.JLabel txtserealkeju;
    private javax.swing.JLabel txtturbo;
    // End of variables declaration//GEN-END:variables
}
